/*______________________________________________________________________________
[]                                                                            []
[] This is a part of the PROJECT: 'ObjBase'                                   []
[] Copyright (C) 1999-2000 by the author(s).                                  []
[] All rights reserved.                                                       []
[] __________________________________________________________________________ []
[]                                                                            []
[] Name:            Interface_Dispatch.cpp                                    []
[] Date:            NA                                                        []
[] Author:          Alex Vershinin, Roman V. Koshelev                         []
[] Description:     Диспетчер для вызова оболочек прикладных функций.         []
[] __________________________________________________________________________ []
[]                                                                            []
[] Attention:       This file is auto created by compiling Interface.h-file   []
[]____________________________________________________________________________*/

#define	USES_OBServer_Interface_h
#define	USES_Problem_Interface_h
#include	"include.h"


//______________________________________________________________________________
//                                                                            []
// Диспетчер вызовов прикладных фунций                                        []
//                                                                            []
void OBServer_Interface (const char* OBServer_Function, const char* InputArgs, const char* OutputArgs, void ** ppData)
{
   DEBUG_STACK_NAME (OBServer_Interface);
// Поиск зарегистрированной функции
   FNC_BEGIN;
   {
   // User
      FNC        (MOD_User_New, "Создание пользователя. Присваивается гостевая группа прав, создаётся корневая папка корзины.");
			FNC_IN  (MOD_User, Login, "Логин создаваемого пользователя.");
			FNC_IN  (MOD_User, Password, "Пароль создаваемого пользователя.");
			FNC_IN  (MOD_User, PasswordConfirm, "Подтверждение пароля.");
			FNC_IN  (MOD_User, PasswordInBrowser, "Использовать возможность автоматического ввода пароля");
			FNC_IN  (MOD_User, FullName, "Полное имя пользователя.");
			FNC_IN  (MOD_User, Email, "E-mail.");
			FNC_OUT (MOD_User, objID, "Идентификатор пользователя.");
			FNC_OUT (MOD_User, ExitCode, "Код возврата.");
			FNC_OUT (MOD_User, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_User_Authorize, "Авторизация пользователей, администраторов системы.");
			FNC_IN  (MOD_User, Login, "Логин.");
			FNC_IN  (MOD_User, Password, "Пароль.");
			FNC_IN  (MOD_User, PasswordInBrowser, "Пароль был введён автоматически (через куки). Допустимо, если у пользователя стоит флаг "PasswordInBrowser".");
			FNC_OUT (MOD_User, PasswordInBrowser, "Использовать возможность автоматического ввода пароля. Если да, устанавливаются куки.");
			FNC_OUT (MOD_User, objID, "Идентификатор пользователя или NA если авторизация провалилась.");
			FNC_OUT (MOD_User, ExitCode, "Код возврата.");
			FNC_OUT (MOD_User, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_User_Enumerate, "Перечисление всех пользователей.");
			FNC_IN  (MOD_User, Login, "Логин пользователя, запрашивающего операцию. Для выполнения операции пользователь должен иметь права получения списка.");
			FNC_IN  (MOD_User, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_User, objFirstNo, "Номер объекта, начиная с которого выводятся объекты функцией Enumerate(). По умолчанию равен 0.");
			FNC_IN  (MOD_User, objLastNo, "Номер объекта, с которого прекращаются выводиться объекты функцией Enumerate(). По умолчанию равен последнему порядковому номеру.");
			FNC_OUT (MOD_User, objIDs, "Массив идентификаторов объектов.");
			FNC_OUT (MOD_User, objNames, "Массив названий объектов.");
			FNC_OUT (MOD_User, objFullNames, "Массив имён пользователей.");
			FNC_OUT (MOD_User, TotalStoredNum, "Сколько всего объектов хранится в базе.");
			FNC_OUT (MOD_User, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз объектов.");
			FNC_OUT (MOD_User, ExitCode, "Код возврата.");
			FNC_OUT (MOD_User, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_User_GetData, "Получение данных о пользователе.");
			FNC_IN  (MOD_User, objID, "Идентификатор пользователя, чья информация запрашивается.");
			FNC_IN  (MOD_User, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами просматривать данные пользователей и обладать более высоким уровнем доступа, или быть самим пользователем.");
			FNC_IN  (MOD_User, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_User, Login, "Логин запрашиваемого пользователя");
			FNC_OUT (MOD_User, FullName, "Полное имя пользователя.");
			FNC_OUT (MOD_User, Email, "Электронный адрес пользователя.");
			FNC_OUT (MOD_User, URL, "URL пользователя.");
			FNC_OUT (MOD_User, Data, "Прочая информацияя, упакованная скриптами по известному им формату в текстовую строку.");
			FNC_OUT (MOD_User, PasswordInBrowser, "Использовать возможность автоматического ввода пароля.");
			FNC_OUT (MOD_User, ReadOnly, "Данные могут быть только прочитаны и не могут быть изменены.");
			FNC_OUT (MOD_User, CreationTime, "Время создания объекта");
			FNC_OUT (MOD_User, ExitCode, "Код возврата.");
			FNC_OUT (MOD_User, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_User_PutData, "Изменение данных о пользователе с идентификатором objID.");
			FNC_IN  (MOD_User, objID, "Идентификатор пользователя, чья информация изменяется.");
			FNC_IN  (MOD_User, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами изменять данные пользователей и более сильным уровнем доступа, чем objID, или быть самим пользователем.");
			FNC_IN  (MOD_User, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_User, NewPassword, "Если поле не пусто, сменить пароль.");
			FNC_IN  (MOD_User, NewPasswordConfirm, "Подтверждение нового пароля.");
			FNC_IN  (MOD_User, PasswordInBrowser, "Использовать возможность автоматического ввода пароля");
			FNC_IN  (MOD_User, FullName, "Полное имя");
			FNC_IN  (MOD_User, Email, "Электронный адрес");
			FNC_IN  (MOD_User, URL, "URL пользователя.");
			FNC_IN  (MOD_User, Data, "Прочая информацияя, упакованная скриптами по известному им формату в текстовую строку.");
			FNC_OUT (MOD_User, ExitCode, "Код возврата.");
			FNC_OUT (MOD_User, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_User_GetRights, "Чтение прав пользователя.");
			FNC_IN  (MOD_User, objID, "Идентификатор пользователя, чьи права запрашиваются.");
			FNC_IN  (MOD_User, Login, "Логин пользователя, запрашивающего операцию. Логин должен обладать правами чтения прав других пользователей и более сильным уровнем доступа, или быть самим пользователем.");
			FNC_IN  (MOD_User, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_User, ExpandGroups, "Требуется ли отдавать набор прав для каждой группы -- LoginGroupRights.");
			FNC_IN  (MOD_User, ExpandRights, "Требуется ли расширять набор прав за счёт всех дочерних (выводимых) прав.");
			FNC_OUT (MOD_User, Login, "Логин запрашиваемого пользователя");
			FNC_OUT (MOD_User, LoginAccessLevel, "Уровень доступа логина");
			FNC_OUT (MOD_User, LoginGroupIDs, "Все группы прав логина.");
			FNC_OUT (MOD_User, LoginGroupNames, "Имена групп права логина.");
			FNC_OUT (MOD_User, LoginGroupTypes, "Типы групп: root, admin, user, прочее. Помогает строить интерфейс в административной зоне.");
			FNC_OUT (MOD_User, LoginGroupRights, "Упакованные в строки данные по правам каждой группы. Формат: "feodID|атрибуты|feodName|feodType\nfeodID|атрибуты|feodName\n...feodID|атрибуты|feodName|feodType"");
			FNC_OUT (MOD_User, LoginOwnRights, "Упакованные в строку данные по личным правам логина. Это те зоны доступа, которые создал сам логин. Формат тоже, что и у LoginGroupRights.");
			FNC_OUT (MOD_User, ObjAccessLevel, "Уровень доступа пользователя.");
			FNC_OUT (MOD_User, ObjGroupIDs, "Если логин принадлежит к группе пользователя и его уровень сильнее, то он может знать о том, что пользователь обладает этой группой. Список таких групп.");
			FNC_OUT (MOD_User, CreationTime, "Время создания объекта");
			FNC_OUT (MOD_User, ReadOnly, "Права могут быть только прочитаны и не могут быть изменены.");
			FNC_OUT (MOD_User, ExitCode, "Код возврата.");
			FNC_OUT (MOD_User, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_User_PutRights, "Изменение прав пользователя с идентификатором objID.");
			FNC_IN  (MOD_User, objID, "Идентификатор пользователя, чьи права изменяются.");
			FNC_IN  (MOD_User, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами изменения прав других пользователей. Чтобы отобрать права надо иметь более сильный уровень доступа.");
			FNC_IN  (MOD_User, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_User, AccessLevel, "Новый уровень доступа пользоваетеля. Уровень доступа не может быть равным или сильнее чем уровень доступа самого логина. Кроме того, более слабый пользователь не может изменить уровень доступа более сильного.");
			FNC_IN  (MOD_User, objIDs, "Права, которые, по мнению логина, должны быть у пользователя. Если логин сильнее, то он может отобрать у пользователя любые группы, которыми обладает сам. Независимо от уровня доступа он может делегировать те группы прав, которыми обладает сам.");
			FNC_OUT (MOD_User, ExitCode, "Код возврата.");
			FNC_OUT (MOD_User, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_User_CheckOwnRights, "Проверка пользователем наличия у себя указанных прав.");
			FNC_IN  (MOD_User, Login, "Логин пользователя, запрашивающего операцию. Для него и проверяются права.");
			FNC_IN  (MOD_User, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_User, FeodNames, "Набор имён зон доступа");
			FNC_IN  (MOD_User, FeodAttributes, "Соответсвующие зонам доступа атрибуты доступа. Строки вида "CLRWD"");
			FNC_OUT (MOD_User, Accesses, "Булевский массив, содержащий ответы на вопросы о возможности доступа к соответствующей зоне с указанными атрибутами.");
			FNC_OUT (MOD_User, ExitCode, "Код возврата.");
			FNC_OUT (MOD_User, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_User_Delete, "Удаление пользователя с идентификатором objID. Удаляются все объекты, которыми он владел. Пользователь удаляется из групп.");
			FNC_IN  (MOD_User, objID, "Идентификатор удаляемого пользователя.");
			FNC_IN  (MOD_User, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами удаления пользователей, и более сильным доступом, чем удаляемый пользователь.");
			FNC_IN  (MOD_User, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_User, ExitCode, "Код возврата.");
			FNC_OUT (MOD_User, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // UserGroup
      FNC        (MOD_UserGroup_New, "Создание группы.");
			FNC_IN  (MOD_UserGroup, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами создания групп. Пользователь заносится в создаваемую группу.");
			FNC_IN  (MOD_UserGroup, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_UserGroup, Name, "Имя создаваемой группы. Если передано пустое или неуникальное имя, то система сама придумывает/изменяет название группы.");
			FNC_IN  (MOD_UserGroup, Type, "Предопределённый тип группы: root, admin, user, прочее. Помогает строить интерфейс в административной зоне.");
			FNC_IN  (MOD_UserGroup, Description, "Описание группы.");
			FNC_IN  (MOD_UserGroup, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей. Группа должна иметь более слабый порог, чем уровень её создателя, чтобы тот мог её править/удалять.");
			FNC_OUT (MOD_UserGroup, objID, "Идентификатор созданной группы.");
			FNC_OUT (MOD_UserGroup, ExitCode, "Код возврата.");
			FNC_OUT (MOD_UserGroup, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_UserGroup_Enumerate, "Перечисление доступных групп.");
			FNC_IN  (MOD_UserGroup, Login, "Логин пользователя, запрашивающего операцию. Для выполнения операции пользователь должен иметь права получения списка.");
			FNC_IN  (MOD_UserGroup, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_UserGroup, objFirstNo, "Номер объекта, начиная с которого выводятся объекты функцией Enumerate(). По умолчанию равен 0.");
			FNC_IN  (MOD_UserGroup, objLastNo, "Номер объекта, с которого прекращаются выводиться объекты функцией Enumerate(). По умолчанию равен последнему порядковому номеру.");
			FNC_OUT (MOD_UserGroup, objIDs, "Массив идентификаторов объектов. Выдаются только те группы, в которых состоит пользователь.");
			FNC_OUT (MOD_UserGroup, objNames, "Массив названий объектов.");
			FNC_OUT (MOD_UserGroup, objTypes, "Массив типов групп: root, admin, user, прочее. Помогает строить интерфейс в административной зоне.");
			FNC_OUT (MOD_UserGroup, objAccessLevelThresholds, "Пороговые значение для уровня доступа пользователей.");
			FNC_OUT (MOD_UserGroup, TotalStoredNum, "Сколько всего объектов хранится в базе.");
			FNC_OUT (MOD_UserGroup, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз объектов.");
			FNC_OUT (MOD_UserGroup, ExitCode, "Код возврата.");
			FNC_OUT (MOD_UserGroup, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_UserGroup_GetData, "Получение данных о группе.");
			FNC_IN  (MOD_UserGroup, objID, "Идентификатор группы, чья информация запрашивается.");
			FNC_IN  (MOD_UserGroup, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами просматривать группы и принадлежать к запрашиваемой группе.");
			FNC_IN  (MOD_UserGroup, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_UserGroup, UserFirstNo, "Номер пользователя внутри групы, начиная с которого перечислять пользователей.");
			FNC_IN  (MOD_UserGroup, UserLastNo, "Номер последнего запрашиваемого пользователя групы.");
			FNC_OUT (MOD_UserGroup, Name, "Имя группы");
			FNC_OUT (MOD_UserGroup, Type, "Предопределённый тип группы: root, admin, user, прочее. Помогает строить интерфейс в административной зоне.");
			FNC_OUT (MOD_UserGroup, Description, "Описание группы");
			FNC_OUT (MOD_UserGroup, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей. Группа должна иметь более слабый порог, чем уровень её создателя, чтобы тот мог её править/удалять.");
			FNC_OUT (MOD_UserGroup, CreationTime, "Время создания объекта");
			FNC_OUT (MOD_UserGroup, FeodIDs, "Набор идентификаторов зон доступа.");
			FNC_OUT (MOD_UserGroup, FeodNames, "Набор имён зон доступа.");
			FNC_OUT (MOD_UserGroup, FeodAttributes, "Соответсвующие зонам доступа атрибуты доступа. Строки вида "CLRWD"");
			FNC_OUT (MOD_UserGroup, UserIDs, "Идентификаторы пользователей-членов группы.");
			FNC_OUT (MOD_UserGroup, UserLogins, "Логины пользователей-членов группы.");
			FNC_OUT (MOD_UserGroup, UserFullNames, "Имена пользователей-членов группы.");
			FNC_OUT (MOD_UserGroup, UserAccessLevels, "Уровни доступа пользователей-членов группы.");
			FNC_OUT (MOD_UserGroup, UserCreationTimes, "Времена создания пользователей-членов группы.");
			FNC_OUT (MOD_UserGroup, UserTotalStoredNum, "Сколько всего пользователей в группе.");
			FNC_OUT (MOD_UserGroup, UserMaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз пользователей группы.");
			FNC_OUT (MOD_UserGroup, ReadOnly, "Данные могут быть только прочитаны и не могут быть изменены.");
			FNC_OUT (MOD_UserGroup, ExitCode, "Код возврата.");
			FNC_OUT (MOD_UserGroup, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_UserGroup_PutData, "Изменение данных группы.");
			FNC_IN  (MOD_UserGroup, objID, "Идентификатор группы, чья информация изменяется.");
			FNC_IN  (MOD_UserGroup, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами изменять группы, принадлежать к изменяемой группе и иметь более сильный уровень доступа, чем пороговое значение группы.");
			FNC_IN  (MOD_UserGroup, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_UserGroup, Name, "Имя группы");
			FNC_IN  (MOD_UserGroup, Type, "Предопределённый тип группы: root, admin, user, прочее. Помогает строить интерфейс в административной зоне.");
			FNC_IN  (MOD_UserGroup, Description, "Описание группы");
			FNC_IN  (MOD_UserGroup, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей. Не может быть сильнее чем уровень логина.");
			FNC_IN  (MOD_UserGroup, FeodIDs, "Набор идентификаторов всех зон доступа группы. Логин должен иметь доступ к этим зонам с соответствующими атрибутами.");
			FNC_IN  (MOD_UserGroup, FeodAttributes, "Соответсвующие зонам доступа атрибуты доступа. Строки вида "CLRWD"");
			FNC_OUT (MOD_UserGroup, ExitCode, "Код возврата.");
			FNC_OUT (MOD_UserGroup, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_UserGroup_Delete, "Удаление группы. У всех пользоваетелй, принадлежащих к группе, она удаляется из списка групп.");
			FNC_IN  (MOD_UserGroup, objID, "Идентификатор удаляемой группы.");
			FNC_IN  (MOD_UserGroup, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать удалять группы, принадлежать к удаляемой группе и иметь более сильный уровень доступа, чем пороговое значение группы.");
			FNC_IN  (MOD_UserGroup, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_UserGroup, ExitCode, "Код возврата.");
			FNC_OUT (MOD_UserGroup, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // Feod
      FNC        (MOD_Feod_New, "Создание зоны доступа. Добавляется в рутовую группу со всеми атрибутами и в список личных прав создателя.");
			FNC_IN  (MOD_Feod, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами создания зон доступа.");
			FNC_IN  (MOD_Feod, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Feod, Name, "Имя создаваемой зоны. Если передано пустое или неуникальное имя, то система сама придумывает/изменяет название зоны доступа.");
			FNC_IN  (MOD_Feod, Type, "Тип создаваемой зоны. Если не указан, равен имени.");
			FNC_IN  (MOD_Feod, Description, "Описание создаваемой зоны.");
			FNC_IN  (MOD_Feod, ParentID, "Зона верхнего уровня. Пользователь должен иметь право создавать дочернии зоны доступа в указанной зоне (обладать правом на эту зону с атрибутом [M]).");
			FNC_IN  (MOD_Feod, ParentName, "Имя зоны верхнего уровня. Используется, когда не указан ParentID.");
			FNC_IN  (MOD_Feod, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей. Зона должна иметь более слабый порог, чем уровень её создателя, чтобы тот мог её править/удалять.");
			FNC_OUT (MOD_Feod, objID, "Идентификатор созданной зоны.");
			FNC_OUT (MOD_Feod, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Feod, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Feod_Enumerate, "Перечисление зон доступа. Перечисяются только те, к которым есть доступ [L].");
			FNC_IN  (MOD_Feod, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь права получения списка [L].");
			FNC_IN  (MOD_Feod, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Feod, ParentID, "Идентификатор феода, потомков которого перечислить.");
			FNC_IN  (MOD_Feod, ParentName, "Используется, если ParentID == NA.");
			FNC_OUT (MOD_Feod, objIDs, "Идентификаторы феодов, включая родительский (objID). Перечисятся только те, к которым есть доступ [L]");
			FNC_OUT (MOD_Feod, objNames, "Названия феодов");
			FNC_OUT (MOD_Feod, objTypes, "Типы феодов, полный путь от корня ("Concept.Feod.Data")");
			FNC_OUT (MOD_Feod, objDescriptions, "Описания феодов");
			FNC_OUT (MOD_Feod, objParentIDs, "Идентификаторы родительских феодов или NA для корня");
			FNC_OUT (MOD_Feod, objThresholds, "Уровни доступа");
			FNC_OUT (MOD_Feod, objExtClassNames, "Названия классов-расширений над соответствующими феодами");
			FNC_OUT (MOD_Feod, objExtIDs, "Идентификаторы объектов-расширений над соответствующими феодами");
			FNC_OUT (MOD_Feod, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Feod, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Feod_Delete, "Удаление зоны доступа. Пользователь должен иметь право удаления [D] и право манипулирования в указанном разделе и его преддке.");
			FNC_IN  (MOD_Feod, Login, "Логин пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Feod, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Feod, objID, "Идентификатор удаляемого объекта.");
			FNC_OUT (MOD_Feod, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Feod, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // InfoDiv
      FNC        (MOD_InfoDiv_New, "Создание информационного раздела.");
			FNC_IN  (MOD_InfoDiv, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами создания разделов в указанной зоне доступа.");
			FNC_IN  (MOD_InfoDiv, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_InfoDiv, Name, "Имя создаваемого раздела. При этом создастся феод с аналогичным именем. Если передано пустое или неуникальное имя, то система сама придумывает/изменяет имя раздела.");
			FNC_IN  (MOD_InfoDiv, Description, "Описание создаваемого раздела.");
			FNC_IN  (MOD_InfoDiv, ParentID, "Родительский раздел.");
			FNC_IN  (MOD_InfoDiv, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей. Раздел должен иметь более слабый порог, чем уровень её создателя, чтобы тот мог его править/удалять.");
			FNC_OUT (MOD_InfoDiv, objID, "Идентификатор созданного раздела.");
			FNC_OUT (MOD_InfoDiv, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoDiv, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_InfoDiv_Enumerate, "Перечисление доступных разделов.");
			FNC_IN  (MOD_InfoDiv, Login, "Логин пользователя, запрашивающего операцию. Для выполнения операции пользователь должен иметь права получения списка.");
			FNC_IN  (MOD_InfoDiv, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_InfoDiv, ParentID, "Раздел, чьи подразделы следует перечислить. Если NA -- используется ParentName.");
			FNC_IN  (MOD_InfoDiv, ParentName, "Раздел, чьи подразделы следует перечислить. Необходимо польностью указать имя: "Concept.Feod.Data.Type.ТЭК.Нефть"");
			FNC_IN  (MOD_InfoDiv, IncludeParent, "Если true, то возвращается и сам ParentID, иначе только его потомки.");
			FNC_IN  (MOD_InfoDiv, FeodAttributes, "Атрибуты доступа к разделу. Будут перечислены только те разделы, доступ пользователя к которым снабжён указанными атрибутами.");
			FNC_IN  (MOD_InfoDiv, FullNameLevel, "Уровень в иерархии концептов, начиная с которого выводится название раздела.");
			FNC_OUT (MOD_InfoDiv, objIDs, "Массив идентификаторов объектов. Выдаются только те разделы, к которым есть доступ с указанными атрибутами.");
			FNC_OUT (MOD_InfoDiv, objNames, "Массив полных названий разделов.");
			FNC_OUT (MOD_InfoDiv, objTypes, "Массив типов разделов ("Concept.Feod.Data.Type.News")");
			FNC_OUT (MOD_InfoDiv, objLevels, "Массив уровней вложенности разделов. У родительского раздела уровень вложенности считается = 0.");
			FNC_OUT (MOD_InfoDiv, objFeodIDs, "Массив идентификаторов соответствующих зон доступа.");
			FNC_OUT (MOD_InfoDiv, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoDiv, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_InfoDiv_Delete, "Удаление раздела.");
			FNC_IN  (MOD_InfoDiv, objID, "Идентификатор удаляемого объекта.");
			FNC_IN  (MOD_InfoDiv, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право удаления [D].");
			FNC_IN  (MOD_InfoDiv, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_InfoDiv, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoDiv, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // InfoObject
      FNC        (MOD_InfoObject_New, "Создание информационного объекта");
			FNC_IN  (MOD_InfoObject, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами создания объектов во всех указанных разделах.");
			FNC_IN  (MOD_InfoObject, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_InfoObject, Name, "Имя создаваемого объекта.");
			FNC_IN  (MOD_InfoObject, Description, "Описание создаваемого объекта.");
			FNC_IN  (MOD_InfoObject, Text, "Полное содержание.");
			FNC_IN  (MOD_InfoObject, InfoSourceID, "Источник информации.");
			FNC_IN  (MOD_InfoObject, URL, "Собственный URL");
			FNC_IN  (MOD_InfoObject, RelatedLinks, "Ссылки по теме");
			FNC_IN  (MOD_InfoObject, divIDs, "К каким информационным разделам будет относиться объект.");
			FNC_IN  (MOD_InfoObject, InfoTime, "Время, приписанное к информационному объекту. Если не указано -- текущее время.");
			FNC_IN  (MOD_InfoObject, AuthorStr, "Имя автора, не являющегося пользователем");
			FNC_OUT (MOD_InfoObject, objID, "Идентификатор созданного объекта.");
			FNC_OUT (MOD_InfoObject, ProxyID, "Для семантической сети -- идентификатор соответствующего прокси-объекта.");
			FNC_OUT (MOD_InfoObject, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoObject, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_InfoObject_Enumerate, "Перечисление информационных объектов. Перечисление идёт от самых молодых объектов к самым старым.");
			FNC_IN  (MOD_InfoObject, Login, "Логин пользователя, запрашивающего операцию. Для выполнения операции пользователь должен иметь право получения списка.");
			FNC_IN  (MOD_InfoObject, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_InfoObject, Time0, "Допустимое время самых молодых объектов. Начало диапазона. По умолчанию = time(0);");
			FNC_IN  (MOD_InfoObject, Time1, "Допустимое время самых старых объектов. Конец диапазона. По умолчанию = (time_t)0;");
			FNC_IN  (MOD_InfoObject, objFirstNo, "Номер объекта, с которого их перечислять.");
			FNC_IN  (MOD_InfoObject, objLastNo, "Номер последнего запрашиваемого объекта.");
			FNC_IN  (MOD_InfoObject, divIDs, "К каким разделам должен принадлежать объект. У пользователя должны быть права получения списка [L] во всех указанных разделах. Объект должен принадлежать сразу всем разделам. Например: "Concept.Feod.Data.Type.News.Промышленность.Власть" & "Concept.Feod.Data.Service.Process.Public" -- что означает опубликованные новости подраздела "Власть". Если не указано -- работать по divNames");
			FNC_IN  (MOD_InfoObject, divNames, "К каким разделам должен принадлежать объект, если не указаны divIDs. Полные имена вида "Concept.Feod.Data.Type.News.Промышленность.Нефть".");
			FNC_IN  (MOD_InfoObject, divLookInSub, "Если true -- перечислять также и объекты из подразделов. Все объекты перечисляются по одному разу.");
			FNC_IN  (MOD_InfoObject, divAttributes, "Строка вида "CLWRD". Перечисляются объекты только тех разделов, доступ к которым снабжён указанными атрибутами.");
			FNC_IN  (MOD_InfoObject, UpdateStatistics, "Надо ли изменять статистику показов/кликов/CTR запрашиваемых объектов. Например, для издательского интерфейса это не надо делать, а на морде сайта -- надо.");
			FNC_IN  (MOD_InfoObject, InfoSourceID, "Если не NA, выдаются только объекты с указанным источником.");
			FNC_IN  (MOD_InfoObject, bNeedTotalStoredNum, "Требуется ли получить общее число объектов, которые могут быть перечислены.");
			FNC_IN  (MOD_InfoObject, bNeedText, "Возвращать ли массив с текстовым содержанием объектов. Если пользователь не имеет право [R] во всех разделах, в которых лежит объект, возвращается строка {{ACCESS DENY}}.");
			FNC_IN  (MOD_InfoObject, bNeedURL, "Возвращать ли массив с ссылками объектов. Если пользователь не имеет право [R] во всех разделах, в которых лежит объект, возвращается строка {{ACCESS DENY}}.");
			FNC_IN  (MOD_InfoObject, bNeedLog, "Надо ли показывать информацию по логу (авторы, публикаторы, ...) (по умолчанию false) реализуемо если логин имеет право {Concept.Feod.Admin.User.Data}[R] просматривать данные пользователей.");
			FNC_OUT (MOD_InfoObject, objIDs, "Массив идентификаторов объектов.");
			FNC_OUT (MOD_InfoObject, objProxyIDs, "Для семантической сети -- массив идентификаторов соответствующих прокси-объектов.");
			FNC_OUT (MOD_InfoObject, objNames, "Массив названий объектов.");
			FNC_OUT (MOD_InfoObject, objDescriptions, "Массив описаний объектов (анонсы).");
			FNC_OUT (MOD_InfoObject, objLogCreatorIDs, "Идентификаторы создателей (или, если таковые не найдены, то владельцев) публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogCreatorLogins, "Логины создателей публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogCreatorNames, "Имена создателей публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogPublisherIDs, "Идентификаторы публикаторов публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogPublisherLogins, "Логины публикаторов публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogPublisherNames, "Имена публикаторов публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogForbidderIDs, "Идентификаторы запретителей публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogForbidderLogins, "Логины запретителей публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogForbidderNames, "Имена запретителей публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogHotterIDs, "Идентификаторы Hotter(ов) публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogHotterLogins, "Логины Hotter(ов) публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objLogHotterNames, "Имена Hotter(ов) публикаций (только если bNeedLog == true).");
			FNC_OUT (MOD_InfoObject, objTexts, "Массив текстовых содержаний объектов. Если bNeedText=false, массив пустых строк. Если нет права [R], {{ACCESS DENY}}");
			FNC_OUT (MOD_InfoObject, objURLs, "Массив собственных web-адресов объектов. Если bNeedURL=false, массив пустых строк. Если нет права [R], {{ACCESS DENY}}");
			FNC_OUT (MOD_InfoObject, objInfoTimes, "Время, приписанное к информационному объекту.");
			FNC_OUT (MOD_InfoObject, objStatShows, "Сколько раз объект был показан");
			FNC_OUT (MOD_InfoObject, objStatClicks, "Сколько раз объект был востребован для просмотра");
			FNC_OUT (MOD_InfoObject, objStatCTRs, "objStatClicks*100/objStatShows");
			FNC_OUT (MOD_InfoObject, TotalStoredNum, "Сколько всего объектов может быть перечислено.");
			FNC_OUT (MOD_InfoObject, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз объектов.");
			FNC_OUT (MOD_InfoObject, ExitCode, "Код возврата (OK BadLogin BadPassword AccessDeny TooManyEnumerate).");
			FNC_OUT (MOD_InfoObject, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_InfoObject_GetData, "Получение данных информационного объекта.");
			FNC_IN  (MOD_InfoObject, Login, "Логин пользователя, запрашивающего операцию. Для выполнения операции пользователь должен иметь право чтения "R" во всех разделах, где находится объект.");
			FNC_IN  (MOD_InfoObject, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_InfoObject, objID, "Идентификатор запрашиваемого информационного объекта.");
			FNC_IN  (MOD_InfoObject, UpdateStatistics, "Надо ли изменять статистику показов/кликов/CTR запрашиваемых объектов. Например, для издательского интерфейса это не надо делать, а на морде сайта -- надо.");
			FNC_IN  (MOD_InfoObject, bNeedLog, "Нужно ли получать лог изменений информационного объекта, для получения требуется доступ [R] к данным пользователей {Concept.Feod.Admin.User.Data}, По умолчанию false.");
			FNC_OUT (MOD_InfoObject, ProxyID, "Для семантической сети -- идентификатор соответствующего прокси-объекта.");
			FNC_OUT (MOD_InfoObject, Name, "Название объекта.");
			FNC_OUT (MOD_InfoObject, Description, "Описание объекта (анонс).");
			FNC_OUT (MOD_InfoObject, Text, "Содержание объекта.");
			FNC_OUT (MOD_InfoObject, URL, "Собственный адрес объекта.");
			FNC_OUT (MOD_InfoObject, RelatedLinks, "Ссылки по теме");
			FNC_OUT (MOD_InfoObject, InfoSourceID, "Источник информации");
			FNC_OUT (MOD_InfoObject, InfoSourceName, "Название источника информации");
			FNC_OUT (MOD_InfoObject, InfoSourceURL, "URL источника информации");
			FNC_OUT (MOD_InfoObject, InfoTime, "Время, приписанное к информационному объекту.");
			FNC_OUT (MOD_InfoObject, StatShow, "Сколько раз объект был показан");
			FNC_OUT (MOD_InfoObject, StatClick, "Сколько раз объект был востребован для просмотра");
			FNC_OUT (MOD_InfoObject, StatCTR, "objStatView*100/objStatShow");
			FNC_OUT (MOD_InfoObject, divIDs, "К каким разделам принадлежит объект.");
			FNC_OUT (MOD_InfoObject, divNames, "Имена разделов.");
			FNC_OUT (MOD_InfoObject, AuthorStr, "Имя автора, не являющегося пользователем");
			FNC_OUT (MOD_InfoObject, OwnerID, "Идентификатор создателя публикации.");
			FNC_OUT (MOD_InfoObject, OwnerLogin, "Логин создателя публикации.");
			FNC_OUT (MOD_InfoObject, OwnerName, "Имя создателя публикации.");
			FNC_OUT (MOD_InfoObject, Log_Action, "Список кодов действий над информационным объектом, если bNeedLog==false -- пустой массив.");
			FNC_OUT (MOD_InfoObject, Log_Description, "Расшифровки кодов действий, если bNeedLog==false -- пустой массив.");
			FNC_OUT (MOD_InfoObject, Log_UserID, "Список идентификаторов пользователей, совершивших действие, если bNeedLog==false -- пустой массив.");
			FNC_OUT (MOD_InfoObject, Log_UserLogin, "Список логинов пользователей, совершивших действие, если bNeedLog==false -- пустой массив.");
			FNC_OUT (MOD_InfoObject, Log_UserName, "Список полных имён пользователей, совершивших действие, если bNeedLog==false -- пустой массив.");
			FNC_OUT (MOD_InfoObject, Log_Time, "Времена совершения действий над информационным объектом, если bNeedLog==false -- пустой массив.");
			FNC_OUT (MOD_InfoObject, Log_Comment, "Строковые комментарии к действиям, если bNeedLog==false -- пустой массив.");
			FNC_OUT (MOD_InfoObject, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoObject, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_InfoObject_PutData, "Изменение данных информационного объекта.");
			FNC_IN  (MOD_InfoObject, Login, "Логин пользователя, запрашивающего операцию. Для выполнения операции пользователь должен иметь право записи "W" во всех разделах, где находится объект.");
			FNC_IN  (MOD_InfoObject, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_InfoObject, objID, "Идентификатор запрашиваемого информационного объекта.");
			FNC_IN  (MOD_InfoObject, Name, "Название объекта.");
			FNC_IN  (MOD_InfoObject, Description, "Описание объекта (анонс).");
			FNC_IN  (MOD_InfoObject, Text, "Содержание объекта.");
			FNC_IN  (MOD_InfoObject, URL, "Собственный адрес объекта.");
			FNC_IN  (MOD_InfoObject, RelatedLinks, "Ссылки по теме");
			FNC_IN  (MOD_InfoObject, InfoSourceID, "Источник информации");
			FNC_IN  (MOD_InfoObject, InfoTime, "Время, приписанное к информационному объекту.");
			FNC_IN  (MOD_InfoObject, divIDs, "К каким разделам, по меннию логина, должен принадлежать объект. Логин не может выкинуть объект из раздела без доступа [D] и добавить в раздел без доступа [C].");
			FNC_IN  (MOD_InfoObject, AuthorStr, "Имя автора, не являющегося пользователем");
			FNC_OUT (MOD_InfoObject, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoObject, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // InfoSource
      FNC        (MOD_InfoSource_New, "Создание источника информации.");
			FNC_IN  (MOD_InfoSource, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право {Concept.Feod.Aux.Sources}[C].");
			FNC_IN  (MOD_InfoSource, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_InfoSource, Name, "Название источника информации.");
			FNC_IN  (MOD_InfoSource, Description, "Описание источника информации.");
			FNC_IN  (MOD_InfoSource, URL, "Web-адрес, по которому находится источник информации.");
			FNC_IN  (MOD_InfoSource, RefreshType, "[int] Интерпретируемый интерфейсом признак, показывающий когда источник обновляет содержание.");
			FNC_IN  (MOD_InfoSource, divIDs, "К каким информационным разделам будет относиться источник. Можно назначать только те разделы, в которых есть право [R] и ([C] или [W]).");
			FNC_OUT (MOD_InfoSource, objID, "Идентификатор созданного объекта.");
			FNC_OUT (MOD_InfoSource, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoSource, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_InfoSource_Enumerate, "Перечисление всех или только доступных пользователю для работы источников информации (т.е. относящихся к разделам, в которых он может создавать или редактировать объекты)");
			FNC_IN  (MOD_InfoSource, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право {Concept.Feod.Aux.Sources}[L].");
			FNC_IN  (MOD_InfoSource, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_InfoSource, objFirstNo, "Номер объекта, начиная с которого выводятся объекты функцией Enumerate(). По умолчанию равен 0.");
			FNC_IN  (MOD_InfoSource, objLastNo, "Номер объекта, до которого включительно выводятся объекты функцией Enumerate(). По умолчанию равен последнему порядковому номеру.");
			FNC_IN  (MOD_InfoSource, ShowAll, "Если true, то выдаётся список всех информационных источников, иначе только тех, которые пользователь может назначать информационным объектам.");
			FNC_IN  (MOD_InfoSource, divID, "Запрашиваемые источники должны относиться к указанному разделу или его потомкам. Если NA, то смотреть во всех разделах {Concept.Feod.Data}.");
			FNC_IN  (MOD_InfoSource, divName, "Может быть использован, если не указан divID.");
			FNC_OUT (MOD_InfoSource, objIDs, "Массив идентификаторов информационных источников. Если ShowAll=false, то выдаются только относящиеся к разделам, в которым у пользователя есть возможность создавать или править объекты (доступ [C] или [W]).");
			FNC_OUT (MOD_InfoSource, objNames, "Массив названий информационных источников.");
			FNC_OUT (MOD_InfoSource, objURLs, "web-адреса.");
			FNC_OUT (MOD_InfoSource, objRefreshTypes, "[int_arr] Интерпретируемый интерфейсом признак, показывающий когда источник обновляет содержание.");
			FNC_OUT (MOD_InfoSource, objDescriptions, "Описания. Выдаются только в случае наличия права {Concept.Feod.Aux.Sources}[R].");
			FNC_OUT (MOD_InfoSource, TotalStoredNum, "Сколько всего объектов может быть перечислено в данных условиях.");
			FNC_OUT (MOD_InfoSource, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз объектов.");
			FNC_OUT (MOD_InfoSource, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoSource, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_InfoSource_GetData, "Получение данных источника информации.");
			FNC_IN  (MOD_InfoSource, objID, "Идентификатор запрашиваемого источника информации.");
			FNC_IN  (MOD_InfoSource, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право {Concept.Feod.Aux.Sources}[R].");
			FNC_IN  (MOD_InfoSource, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_InfoSource, Name, "Название источника.");
			FNC_OUT (MOD_InfoSource, Description, "Описание источника информации.");
			FNC_OUT (MOD_InfoSource, URL, "Web-адрес, по которому находится источник информации.");
			FNC_OUT (MOD_InfoSource, RefreshType, "[int] Интерпретируемый интерфейсом признак, показывающий когда источник обновляет содержание.");
			FNC_OUT (MOD_InfoSource, divIDs, "К каким информационным разделам относится источник. Показываются только те разделы, в которых пользователь может читать информацию, т.е. имеет доступ [R].");
			FNC_OUT (MOD_InfoSource, divNames, "Названия разделов, к которым относится источник.");
			FNC_OUT (MOD_InfoSource, ShowCount, "Сколько раз были показаны объекты этого источника.");
			FNC_OUT (MOD_InfoSource, ClickCount, "Сколько раз были просмотрены объекты этого источника.");
			FNC_OUT (MOD_InfoSource, CTR, "ClickCount*100/ShowCount");
			FNC_OUT (MOD_InfoSource, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoSource, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_InfoSource_PutData, "Изменение данных источника информации.");
			FNC_IN  (MOD_InfoSource, objID, "Идентификатор изменяемого источника информации.");
			FNC_IN  (MOD_InfoSource, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право {Concept.Feod.Aux.Sources}[R].");
			FNC_IN  (MOD_InfoSource, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_InfoSource, Name, "Название источника.");
			FNC_IN  (MOD_InfoSource, Description, "Описание источника информации.");
			FNC_IN  (MOD_InfoSource, URL, "Web-адрес, по которому находится источник информации.");
			FNC_IN  (MOD_InfoSource, RefreshType, "[int] Интерпретируемый интерфейсом признак, показывающий когда источник обновляет содержание.");
			FNC_IN  (MOD_InfoSource, divIDs, "К каким информационным разделам относится источник. Можно назначать только те разделы, в которых есть право [R] и ([C] или [W]).");
			FNC_OUT (MOD_InfoSource, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoSource, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_InfoSource_Delete, "Удаление источника информации. Источник корректно удалется из разделов и информационных объектов.");
			FNC_IN  (MOD_InfoSource, objID, "Идентификатор удаляемого источника.");
			FNC_IN  (MOD_InfoSource, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право {Concept.Feod.Aux.Sources}[D].");
			FNC_IN  (MOD_InfoSource, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_InfoSource, ExitCode, "Код возврата.");
			FNC_OUT (MOD_InfoSource, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // WebFolder
      FNC        (MOD_WebFolder_New, "Создание папки.");
			FNC_IN  (MOD_WebFolder, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь права создание [C] и [m].");
			FNC_IN  (MOD_WebFolder, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_WebFolder, Name, "Имя папки.");
			FNC_IN  (MOD_WebFolder, Description, "Описание создаваемой папки");
			FNC_IN  (MOD_WebFolder, ParentID, "Родительская папка.");
			FNC_IN  (MOD_WebFolder, ParentName, "Имя родительской папки, используется, если ParentID == NA;");
			FNC_IN  (MOD_WebFolder, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей. Директория должна иметь более слабый порог, чем уровень её создателя, чтобы тот мог её править/удалять.");
			FNC_IN  (MOD_WebFolder, GroupIDs, "К каким группам сразу же отнести созданный феод.							[!! пока не работает]");
			FNC_IN  (MOD_WebFolder, GroupAttributes, "С какими правами доступа к указанным группам отнести созданный феод. [!! пока не работает]");
			FNC_OUT (MOD_WebFolder, objID, "Идентификатор созданного объекта.");
			FNC_OUT (MOD_WebFolder, ExitCode, "Код возврата.");
			FNC_OUT (MOD_WebFolder, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_WebFolder_Enumerate, "Перечисление папок. Возвращаются только те папки, которые могут быть просмотрены, т.е. к которым есть доступ [L]");
			FNC_IN  (MOD_WebFolder, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь права получения списка [L].");
			FNC_IN  (MOD_WebFolder, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_WebFolder, objFirstNo, "Номер объекта, начиная с которого выводятся объекты функцией Enumerate(). По умолчанию равен 0.");
			FNC_IN  (MOD_WebFolder, objLastNo, "Номер объекта, до которого включительно выводятся объекты функцией Enumerate(). По умолчанию равен последнему порядковому номеру.");
			FNC_IN  (MOD_WebFolder, ParentID, "Родительская папка.");
			FNC_IN  (MOD_WebFolder, ParentName, "Имя родительской папки, используется, если ParentID == NA;");
			FNC_IN  (MOD_WebFolder, IncludeParent, "Если true, то возвращается и сам ParentID, иначе только его потомки. Если родитель включается, то он идёт в массиве objIDs первым.");
			FNC_IN  (MOD_WebFolder, AllDescendants, "Если false, то возвращаются только дочернии папки, иначе -- все папки-потомки.");
			FNC_IN  (MOD_WebFolder, FeodAttributes, "Атрибуты доступа к папкам. Будут перечислены только те папки, доступ пользователя к которым снабжён указанными атрибутами.");
			FNC_IN  (MOD_WebFolder, FullNameLevel, "Уровень в иерархии концептов, начиная с которого выводится названия папок.");
			FNC_OUT (MOD_WebFolder, objIDs, "Массив идентификаторов папок.");
			FNC_OUT (MOD_WebFolder, objNames, "Массив названий папок.");
			FNC_OUT (MOD_WebFolder, objTypes, "Массив типов соответствующих концептов-феодов ("Concept.Feod.Files.Site.Public")");
			FNC_OUT (MOD_WebFolder, objLevels, "Массив уровней вложенности папок. У родительской папки уровень вложенности считается = 0.");
			FNC_OUT (MOD_WebFolder, TotalStoredNum, "Сколько всего объектов может быть перечислено в данных условиях.");
			FNC_OUT (MOD_WebFolder, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз объектов.");
			FNC_OUT (MOD_WebFolder, ExitCode, "Код возврата.");
			FNC_OUT (MOD_WebFolder, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_WebFolder_GetData, "Получение данных папки.");
			FNC_IN  (MOD_WebFolder, objID, "Идентификатор запрашиваемого объекта.");
			FNC_IN  (MOD_WebFolder, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право чтения [R].");
			FNC_IN  (MOD_WebFolder, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_WebFolder, Name, "Название папки.");
			FNC_OUT (MOD_WebFolder, FullName, "Полное название папки.");
			FNC_OUT (MOD_WebFolder, Description, "Описание папки.");
			FNC_OUT (MOD_WebFolder, ExitCode, "Код возврата.");
			FNC_OUT (MOD_WebFolder, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_WebFolder_PutData, "Изменение данных папки.");
			FNC_IN  (MOD_WebFolder, objID, "Идентификатор изменяемого объекта.");
			FNC_IN  (MOD_WebFolder, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право записи [W].");
			FNC_IN  (MOD_WebFolder, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_WebFolder, Name, "Новое имя объекта.");
			FNC_IN  (MOD_WebFolder, Description, "Описание папки.");
			FNC_OUT (MOD_WebFolder, ExitCode, "Код возврата.");
			FNC_OUT (MOD_WebFolder, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_WebFolder_Delete, "Удаление папки.");
			FNC_IN  (MOD_WebFolder, objID, "Идентификатор удаляемого объекта.");
			FNC_IN  (MOD_WebFolder, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право удаления [D].");
			FNC_IN  (MOD_WebFolder, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_WebFolder, ExitCode, "Код возврата.");
			FNC_OUT (MOD_WebFolder, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // WebFile
      FNC        (MOD_WebFile_New, "Создание файла");
			FNC_IN  (MOD_WebFile, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами создания файлов во всех указанных папках.");
			FNC_IN  (MOD_WebFile, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_WebFile, Name, "Имя создаваемого файла.");
			FNC_IN  (MOD_WebFile, Description, "Описание создаваемого файла.");
			FNC_IN  (MOD_WebFile, Name_Upload, "Имя, под которым файл загружался.");
			FNC_IN  (MOD_WebFile, OS_Path, "Полный путь к тому месту, где скрипты будут хранить копию файла.");
			FNC_IN  (MOD_WebFile, OS_Ext, "Расширение файла. Полное имя OS-копии файла получится = <OS_Path><objID>.<OS_ext>");
			FNC_IN  (MOD_WebFile, MIMEType, "MIME-тип, например: "image/jpeg", "object-link/InfoObject"");
			FNC_IN  (MOD_WebFile, IconType, "Интерпретируемое скриптами значение, для отображения иконки. Строка.");
			FNC_IN  (MOD_WebFile, PlainTextData, "Образ текстового содержания файла, если возможно.");
			FNC_IN  (MOD_WebFile, BinaryData, "Бинарное содержимое файла.");
			FNC_IN  (MOD_WebFile, folderIDs, "К каким папкам будет относиться объект.");
			FNC_OUT (MOD_WebFile, objID, "Идентификатор созданного объекта.");
			FNC_OUT (MOD_WebFile, ExitCode, "Код возврата.");
			FNC_OUT (MOD_WebFile, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_WebFile_Enumerate, "Перечисление файлов. Перечисление идёт в алфавитном порядке.");
			FNC_IN  (MOD_WebFile, Login, "Логин пользователя, запрашивающего операцию. Для выполнения операции пользователь должен иметь право получения списка.");
			FNC_IN  (MOD_WebFile, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_WebFile, objFirstNo, "Номер объекта, с которого их перечислять.");
			FNC_IN  (MOD_WebFile, objLastNo, "Номер последнего запрашиваемого объекта.");
			FNC_IN  (MOD_WebFile, folderID, "К какой папке должен принадлежать файл. Если не указано -- работать по folderName.");
			FNC_IN  (MOD_WebFile, folderName, "К папке с каким именем должен принадлежать файл, если не указан folderID. Полное имя вида "Concept.Feod.Files.Site".");
			FNC_IN  (MOD_WebFile, UpdateStatistics, "Надо ли изменять статистику показов/кликов/CTR запрашиваемых файлов.");
			FNC_OUT (MOD_WebFile, objIDs, "Массив идентификаторов объектов.");
			FNC_OUT (MOD_WebFile, objNames, "Массив названий объектов.");
			FNC_OUT (MOD_WebFile, objOSNames, "Имена, под которыми файлы дублируются на сервере, например, files/435662.jpg");
			FNC_OUT (MOD_WebFile, objIconTypes, "Интерпретируемые скриптами значения, для отображения иконок. Строки.");
			FNC_OUT (MOD_WebFile, objDescriptions, "Массив описаний объектов (анонсы).");
			FNC_OUT (MOD_WebFile, objCreationTimes, "Времена создания файлов.");
			FNC_OUT (MOD_WebFile, objStatShows, "Сколько раз файл был показан");
			FNC_OUT (MOD_WebFile, objStatClicks, "Сколько раз файл был востребован для просмотра");
			FNC_OUT (MOD_WebFile, objStatCTRs, "objStatClicks*100/objStatShows");
			FNC_OUT (MOD_WebFile, TotalStoredNum, "Сколько всего файлов может быть перечислено.");
			FNC_OUT (MOD_WebFile, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз файлов.");
			FNC_OUT (MOD_WebFile, ExitCode, "Код возврата.");
			FNC_OUT (MOD_WebFile, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_WebFile_GetData, "Получение данных файла");
			FNC_IN  (MOD_WebFile, Login, "Логин пользователя, запрашивающего операцию. Для выполнения операции пользователь должен иметь право чтения "R" хотя бы в одной папке, содержащей файл.");
			FNC_IN  (MOD_WebFile, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_WebFile, objID, "Идентификатор запрашиваемого информационного объекта.");
			FNC_IN  (MOD_WebFile, UpdateStatistics, "Надо ли изменять статистику показов/кликов/CTR.");
			FNC_IN  (MOD_WebFile, NeedBinaryData, "Нужно ли возвращать бинарное содержимое.");
			FNC_IN  (MOD_WebFile, NeedPlainTextData, "Нужно ли возвращать текстовый образ.");
			FNC_OUT (MOD_WebFile, Name, "Название файла.");
			FNC_OUT (MOD_WebFile, Name_Upload, "Имя, под которым файл загружался.");
			FNC_OUT (MOD_WebFile, Name_OS, "Имя, под которым файл дублируется на сервере, например, files/435662.jpg");
			FNC_OUT (MOD_WebFile, Description, "Описание файла.");
			FNC_OUT (MOD_WebFile, CreationTime, "Время создание файла.");
			FNC_OUT (MOD_WebFile, Version, "Число модификаций файла.");
			FNC_OUT (MOD_WebFile, MIMEType, "MIME-тип, например: "image/jpeg", "object-link/InfoObject"");
			FNC_OUT (MOD_WebFile, IconType, "Интерпретируемое скриптами значение, для отображения иконки. Строка.");
			FNC_OUT (MOD_WebFile, BinaryData, "Бинарное содержимое файла, если необходимо.");
			FNC_OUT (MOD_WebFile, PlainTextData, "Образ текстового содержания файла, если необходимо.");
			FNC_OUT (MOD_WebFile, OwnerID, "Создатель файла. [User]");
			FNC_OUT (MOD_WebFile, folderIDs, "К каким папкам относится файл. (Перечисляются только те, к которым есть доступ [L])");
			FNC_OUT (MOD_WebFile, folderNames, "Имена папок.");
			FNC_OUT (MOD_WebFile, StatShow, "Сколько раз объект был показан");
			FNC_OUT (MOD_WebFile, StatClick, "Сколько раз объект был востребован для просмотра");
			FNC_OUT (MOD_WebFile, StatCTR, "objStatView*100/objStatShow");
			FNC_OUT (MOD_WebFile, ExitCode, "Код возврата.");
			FNC_OUT (MOD_WebFile, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_WebFile_PutData, "Изменение данных файла.");
			FNC_IN  (MOD_WebFile, Login, "Логин пользователя, запрашивающего операцию. Для выполнения операции пользователь должен иметь право записи "W" хотя бы в одной папке, содержащей файл или быть владельцем файла.");
			FNC_IN  (MOD_WebFile, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_WebFile, objID, "Идентификатор запрашиваемого информационного файла.");
			FNC_IN  (MOD_WebFile, Name, "Новое имя файла.");
			FNC_IN  (MOD_WebFile, Description, "Описание файла.");
			FNC_IN  (MOD_WebFile, MIMEType, "MIME-тип, например: "image/jpeg", "object-link/InfoObject"");
			FNC_IN  (MOD_WebFile, IconType, "Интерпретируемое скриптами значение, для отображения иконки. Строка.");
			FNC_IN  (MOD_WebFile, ContentChanged, "Если true, значит изменяется содержимое и учитываются поля Name_Upload, OS_Path, OS_Ext, BinaryData и PlainTextData.");
			FNC_IN  (MOD_WebFile, Name_Upload, "Имя, под которым загружается файл.");
			FNC_IN  (MOD_WebFile, OS_Path, "Полный путь к тому месту, где скрипты будут хранить копию файла.");
			FNC_IN  (MOD_WebFile, OS_Ext, "Расширение файла. Полное имя OS-копии файла получится = <OS_Path><objID>.<OS_ext>");
			FNC_IN  (MOD_WebFile, PlainTextData, "Образ текстового содержания файла, учитывается если ContentChanged==true.");
			FNC_IN  (MOD_WebFile, BinaryData, "Бинарное содержимое файла, учитывается если ContentChanged==true.");
			FNC_IN  (MOD_WebFile, folderIDs, "К каким папкам, по меннию логина, должен отностится файл. Логин не может выкинуть файл из папки без доступа [D] и добавить в папку без доступа [C]. Файл обязан лежать хотя-бы в одной папке.");
			FNC_OUT (MOD_WebFile, ExitCode, "Код возврата.");
			FNC_OUT (MOD_WebFile, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // FullTextIndex
      FNC        (MOD_FullTextIndex_Enumerate, "Поиск по объектам базы данных");
			FNC_IN  (MOD_FullTextIndex, Login, "Логин пользователя, запрашивающего операцию. Будут показаны только те объекты, на которые есть права [R].");
			FNC_IN  (MOD_FullTextIndex, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_FullTextIndex, Request, "Поисковый запрос.");
			FNC_IN  (MOD_FullTextIndex, Time0, "Допустимое время самых молодых объектов. Начало диапазона. По умолчанию = time(0);");
			FNC_IN  (MOD_FullTextIndex, Time1, "Допустимое время самых старых объектов. Конец диапазона. По умолчанию = (time_t)0;");
			FNC_IN  (MOD_FullTextIndex, feodIDs, "Список зон доступа, к которым должны относитьсянайденные объекты");
			FNC_IN  (MOD_FullTextIndex, objFirstNo, "Номер объекта, с которого их перечислять.");
			FNC_IN  (MOD_FullTextIndex, objLastNo, "Номер последнего запрашиваемого объекта.");
			FNC_IN  (MOD_FullTextIndex, nLookAhead, "На сколько найденных объектов заглядывать вперёд.[=0]");
			FNC_IN  (MOD_FullTextIndex, bNeedDescription, "Требуется ли описание объектов, или достаточно только имени.");
			FNC_OUT (MOD_FullTextIndex, objClasses, "Массив классов найденных объектов");
			FNC_OUT (MOD_FullTextIndex, objIDs, "Массив идентификаторов найденных объектов.");
			FNC_OUT (MOD_FullTextIndex, objNames, "Массив названий найденных объектов.");
			FNC_OUT (MOD_FullTextIndex, objDescriptions, "Массив описаний найденных объектов (анонсы).");
			FNC_OUT (MOD_FullTextIndex, objTimes, "Массив времён обновления в индексах найденных объектов.");
			FNC_OUT (MOD_FullTextIndex, objWeights, "Массив весов-рангов найденных объектов.");
			FNC_OUT (MOD_FullTextIndex, objPlacements, "Массив объектов, выведенных из феодов, например разделов. Формат: {class|id|name\nclass|id|name, ...}");
			FNC_OUT (MOD_FullTextIndex, RequestLemma, "Преобразованный поисковый запрос.");
			FNC_OUT (MOD_FullTextIndex, TotalStoredNum, "Сколько всего объектов найдено и может быть показано данному пользователю.");
			FNC_OUT (MOD_FullTextIndex, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз объектов.");
			FNC_OUT (MOD_FullTextIndex, ExitCode, "Код возврата");
			FNC_OUT (MOD_FullTextIndex, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // Relation
      FNC        (MOD_Relation_New, "Создание семантического отношения.");
			FNC_IN  (MOD_Relation, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь права создания отношений [C].");
			FNC_IN  (MOD_Relation, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Relation, Name, "Имя");
			FNC_IN  (MOD_Relation, SysName, "Системное название отношения, строится как переменная С++");
			FNC_IN  (MOD_Relation, Description, "Описание отношения");
			FNC_IN  (MOD_Relation, FieldNames, "Названия полей");
			FNC_IN  (MOD_Relation, FieldTypes, "Типы полей ("object" "byte" "int" "bool" "time" "string" "float")");
			FNC_IN  (MOD_Relation, FieldSysNames, "Системные имена полей, строятся как переменные С++");
			FNC_IN  (MOD_Relation, FieldDescriptions, "Описания полей");
			FNC_IN  (MOD_Relation, FieldInterfaceTypes, "Типы полей, интерпретируемые интерфейсом");
			FNC_IN  (MOD_Relation, FeodIDs, "Зоны доступа, к которым принадлежит отношение -- см. {Concept.Feod.Semantic}");
			FNC_IN  (MOD_Relation, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей к объекту.");
			FNC_OUT (MOD_Relation, objID, "Идентификатор созданного объекта.");
			FNC_OUT (MOD_Relation, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Relation, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Relation_Enumerate, "Перечисление всех доступных семантических отношений.");
			FNC_IN  (MOD_Relation, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь права получения списка [L].");
			FNC_IN  (MOD_Relation, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Relation, objFirstNo, "Номер объекта, начиная с которого выводятся объекты функцией Enumerate(). По умолчанию равен 0.");
			FNC_IN  (MOD_Relation, objLastNo, "Номер объекта, до которого включительно выводятся объекты функцией Enumerate(). По умолчанию равен последнему порядковому номеру.");
			FNC_IN  (MOD_Relation, FeodIDs, "К каким зонам обязательно должны принадлежать отношения.");
			FNC_IN  (MOD_Relation, FeodNames, "Используется, если массив FeodIDs пуст. Имена вида "{Concept.Feod.Semantic...}"");
			FNC_IN  (MOD_Relation, Attributes, "Атрибуты доступа. Будут перечислены только те отношения, доступ пользователя к которым снабжён указанными атрибутами. Атрибут [L] включается в запрос автоматически.");
			FNC_OUT (MOD_Relation, objIDs, "Массив идентификаторов перечисленных объектов.");
			FNC_OUT (MOD_Relation, objNames, "Массив названий перечисленных объектов.");
			FNC_OUT (MOD_Relation, objVersions, "Массив версий отношений");
			FNC_OUT (MOD_Relation, objSysNames, "Системные названия отношений");
			FNC_OUT (MOD_Relation, objDescriptions, "Массив описаний перечисленных объектов.");
			FNC_OUT (MOD_Relation, TotalStoredNum, "Сколько всего объектов может быть перечислено в данных условиях.");
			FNC_OUT (MOD_Relation, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз объектов.");
			FNC_OUT (MOD_Relation, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Relation, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Relation_GetData, "Получение данных о семантическом отношении.");
			FNC_IN  (MOD_Relation, objID, "Идентификатор запрашиваемого объекта.");
			FNC_IN  (MOD_Relation, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право чтения отношений [R].");
			FNC_IN  (MOD_Relation, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_Relation, SysName, "Системное название отношения");
			FNC_OUT (MOD_Relation, Name, "Название отношения.");
			FNC_OUT (MOD_Relation, Version, "Версия отношения.");
			FNC_OUT (MOD_Relation, Description, "Описание отношения");
			FNC_OUT (MOD_Relation, FieldNames, "Названия полей");
			FNC_OUT (MOD_Relation, FieldTypes, "Типы полей ("object" "byte" "int" "bool" "time" "string" "float")");
			FNC_OUT (MOD_Relation, FieldSysNames, "Системные имена полей, строятся как переменные С++");
			FNC_OUT (MOD_Relation, FieldDescriptions, "Описания полей");
			FNC_OUT (MOD_Relation, FieldInterfaceTypes, "Типы полей, интерпретируемые интерфейсом");
			FNC_OUT (MOD_Relation, FeodIDs, "Зоны доступа, к которым принадлежит отношение");
			FNC_OUT (MOD_Relation, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей к объекту.");
			FNC_OUT (MOD_Relation, ReadOnly, "Имеет ли пользователь право редактировать объект");
			FNC_OUT (MOD_Relation, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Relation, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Relation_PutData, "Изменение данных семантического отношения.");
			FNC_IN  (MOD_Relation, objID, "Идентификатор изменяемого объекта.");
			FNC_IN  (MOD_Relation, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право записи [W].");
			FNC_IN  (MOD_Relation, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Relation, SysName, "Системное название отношения, строится как переменная С++");
			FNC_IN  (MOD_Relation, Name, "Название отношения");
			FNC_IN  (MOD_Relation, Description, "Описание отношения");
			FNC_IN  (MOD_Relation, FieldNames, "Названия полей");
			FNC_IN  (MOD_Relation, FieldSysNames, "Системные имена полей, строятся как переменные С++");
			FNC_IN  (MOD_Relation, FieldDescriptions, "Описания полей");
			FNC_IN  (MOD_Relation, FieldInterfaceTypes, "Типы полей, интерпретируемые интерфейсом");
			FNC_IN  (MOD_Relation, FeodIDs, "Зоны доступа, к которым принадлежит отношение");
			FNC_IN  (MOD_Relation, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей к объекту.");
			FNC_OUT (MOD_Relation, Version, "Версия отношения.");
			FNC_OUT (MOD_Relation, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Relation, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Relation_ChangeField, "Изменение полей семантического отношения.");
			FNC_IN  (MOD_Relation, objID, "Идентификатор изменяемого объекта.");
			FNC_IN  (MOD_Relation, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право записи [W].");
			FNC_IN  (MOD_Relation, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Relation, ChangeType, "0 - вставить новое поле, 1 - удалить поле, 2 - переместить поле, 3 - переименовать.");
			FNC_IN  (MOD_Relation, FieldID, "Идентифиукатор (позиция) поля. Чтобы вставить в конец надо просто передать большое значение.");
			FNC_IN  (MOD_Relation, FieldPos, "Куда поле перемещать. Используется для указания, куда перемещать поле.");
			FNC_IN  (MOD_Relation, FieldName, "Новое имя поля или имя нового поля. Используется при вставки нового и переименовании старого поля.");
			FNC_IN  (MOD_Relation, FieldSysName, "Новое системное имя поля или системное имя нового поля, строится как переменная С++. Используется при вставки нового и переименовании старого поля.");
			FNC_IN  (MOD_Relation, FieldDescription, "Новое описание поля или описание нового поля. Используется при вставки нового и переименовании старого поля.");
			FNC_IN  (MOD_Relation, FieldInterfaceType, "Тип поля, интерпретируемое интерфейсом");
			FNC_OUT (MOD_Relation, Version, "Версия отношения.");
			FNC_OUT (MOD_Relation, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Relation, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Relation_Delete, "Удаление семантического отношения.");
			FNC_IN  (MOD_Relation, objID, "Идентификатор удаляемого отношения.");
			FNC_IN  (MOD_Relation, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право удаления [D] отношения во всех зонах доступа.");
			FNC_IN  (MOD_Relation, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_OUT (MOD_Relation, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Relation, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // Linkage
      FNC        (MOD_Linkage_New, "Создание связи.");
			FNC_IN  (MOD_Linkage, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь права чтения [R] во всех феодах соответствующего отношения.");
			FNC_IN  (MOD_Linkage, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Linkage, RelationID, "Идентификатор отношения, на основе которого строится связь.");
			FNC_IN  (MOD_Linkage, RelationVersion, "Версия отношения (если -1, то игнорируется).");
			FNC_IN  (MOD_Linkage, ProxyIDs, "Идентификаторы связываемых прокси-объектов. К ним должен быть доступ [W].");
			FNC_IN  (MOD_Linkage, Values, "Поля-значения (строки)");
			FNC_IN  (MOD_Linkage, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей. Объект должен иметь более слабый порог, чем уровень её создателя, чтобы тот мог её править/удалять.");
			FNC_OUT (MOD_Linkage, objID, "Идентификатор созданной связи.");
			FNC_OUT (MOD_Linkage, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Linkage, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Linkage_Enumerate, "Перечисление всех связей, относящихся к указанному прокси-объекту.");
			FNC_IN  (MOD_Linkage, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь права получения списка [L] во всех феодах соответствующего отношения или [LR], если bNeedFields.");
			FNC_IN  (MOD_Linkage, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Linkage, objID, "Идентификатор объекта-прокси, чьи связи запрашиваются. Если NA -- все связи. К парному реальному объекту должен быть доступ [R].");
			FNC_IN  (MOD_Linkage, UseRelationID, "Если false (по умолчаанию), то выводятся все связи, иначе только те, которые имеют тип RelatonID.");
			FNC_IN  (MOD_Linkage, RelationID, "Учитывается только если UseRelationID==true. Идентификатор отношения (типа связи). Выводятся только связи, реализующие указанное отношение. К отношениию должен быть доступ [L].");
			FNC_IN  (MOD_Linkage, bNeedFields, "Возвращать ли массив со значениями указанных полей. (По-умолчанию false). Если указано, то требуется право [R].");
			FNC_IN  (MOD_Linkage, FieldIndices, "Значения каких полей связей возвращать (используется при bNeedFields).");
			FNC_IN  (MOD_Linkage, RelationSysName, "Учитывается только если UseRelationID==true и если не указан RelationID.");
			FNC_IN  (MOD_Linkage, objFirstNo, "Номер объекта, начиная с которого выводятся объекты функцией Enumerate(). По умолчанию равен 0.");
			FNC_IN  (MOD_Linkage, objLastNo, "Номер объекта, до которого включительно выводятся объекты функцией Enumerate(). По умолчанию равен последнему порядковому номеру.");
			FNC_OUT (MOD_Linkage, objIDs, "Массив идентификаторов связей, в которых участвует объект. Исключаются те связи, которые содержат объекты, к котороым нет доступа [R].");
			FNC_OUT (MOD_Linkage, objFieldsValues, "Значения указанных полей в виде строк. Упаковано последовательно -- сначала все поля i-й, потом i+1-й связи. Пустой массив если bNeedFields==false. Если пользователь не имеет право чтения связи, возвращается строка "{{ACCESS DENY}}".");
			FNC_OUT (MOD_Linkage, objRelationIDs, "Массив идентификаторов соответствующих отношений.");
			FNC_OUT (MOD_Linkage, TotalStoredNum, "Сколько всего связей может быть перечислено в данных условиях.");
			FNC_OUT (MOD_Linkage, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз объектов.");
			FNC_OUT (MOD_Linkage, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Linkage, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Linkage_GetData, "Получение данных о семантической связи. Должны быть права чтения на отношение и на все объекты.");
			FNC_IN  (MOD_Linkage, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право чтения [R].");
			FNC_IN  (MOD_Linkage, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Linkage, objID, "Идентификатор запрашиваемой связи.");
			FNC_OUT (MOD_Linkage, FieldTypes, "Типы полей ("object" "byte" "int" "bool" "time" "string" "float")");
			FNC_OUT (MOD_Linkage, FieldValues, "Строковые значения полей, если тип не "object"");
			FNC_OUT (MOD_Linkage, FieldObjectProxyIDs, "Идентификаторы прокси-объектов, если тип="object". NA если поле пусто.");
			FNC_OUT (MOD_Linkage, FieldObjectClasses, "Классы реальных объектов-полей, если тип поля="object". Пустая строка если поле пусто.");
			FNC_OUT (MOD_Linkage, FieldObjectIDs, "Идентификаторы реальных объектов-полей, если тип поля="object". NA если поле пусто.");
			FNC_OUT (MOD_Linkage, FieldObjectNames, "Имена реальных объектов-полей, если тип поля="object". Если база не может узнать имя объекта, возвращается "{{UNKNOWN NAME}}". "{{NA}}" если поле пусто.");
			FNC_OUT (MOD_Linkage, AccessLevelThreshold, "Пороговое значение уровня доступа пользователей.");
			FNC_OUT (MOD_Linkage, ReadOnly, "Имеет ли пользователь право редактировать объект");
			FNC_OUT (MOD_Linkage, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Linkage, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Linkage_GetRealObjectByProxyID, "Получение реального объекта по идентификатору прокси");
			FNC_IN  (MOD_Linkage, objID, "Прокси объект.");
			FNC_OUT (MOD_Linkage, RealObjectClassName, "Класс реального объекта");
			FNC_OUT (MOD_Linkage, RealObjectID, "Идентификатор реального объекта");
			FNC_OUT (MOD_Linkage, RealObjectName, "Имя реального объекта");
			FNC_OUT (MOD_Linkage, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Linkage, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Linkage_PutData, "Изменение полей семантической связи.");
			FNC_IN  (MOD_Linkage, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право записи [W].");
			FNC_IN  (MOD_Linkage, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Linkage, objID, "Идентификатор связи.");
			FNC_IN  (MOD_Linkage, RelationVersion, "Версия отношения (если -1, то игнорируется).");
			FNC_IN  (MOD_Linkage, ProxyIDs, "Идентификаторы связываемых прокси-объектов. К ним должен быть доступ [W].");
			FNC_IN  (MOD_Linkage, Values, "Поля-значения (строки)");
			FNC_OUT (MOD_Linkage, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Linkage, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_Linkage_Delete, "Удаление семантической связи. Должен быть доступ [D] к отношению и [W] ко всем объекта-участникам.");
			FNC_IN  (MOD_Linkage, Login, "Логин пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Linkage, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_Linkage, objID, "Идентификатор связи.");
			FNC_OUT (MOD_Linkage, ExitCode, "Код возврата.");
			FNC_OUT (MOD_Linkage, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // MetaObject
      FNC        (MOD_MetaObject_New, "Создание Метаобъектов.");
			FNC_IN  (MOD_MetaObject, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь права создания метаобъектов [C] в указанных зонах.");
			FNC_IN  (MOD_MetaObject, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_MetaObject, Type, "Тип метаобъекта.");
			FNC_IN  (MOD_MetaObject, Name, "Имя метаобъекта.");
			FNC_IN  (MOD_MetaObject, SysName, "Системное имя метаобъекта, строится как переменная С++. Если не пусто, то имя должно быть уникально внутри типа.");
			FNC_IN  (MOD_MetaObject, FeodIDs, "Зоны доступа, к которым будет принадлежать метаобъект {Concept.Feod.Semantic}. Должна быть указана хотя-бы одна зона.");
			FNC_OUT (MOD_MetaObject, objID, "Идентификатор созданного объекта.");
			FNC_OUT (MOD_MetaObject, ProxyID, "Для семантической сети -- идентификатор соответствующего прокси-объекта.");
			FNC_OUT (MOD_MetaObject, ExitCode, "Код возврата.");
			FNC_OUT (MOD_MetaObject, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_MetaObject_Enumerate, "Перечисление всех доступных Метаобъектов.");
			FNC_IN  (MOD_MetaObject, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь права получения списка [L].");
			FNC_IN  (MOD_MetaObject, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_MetaObject, TypePrefix, "Перечислятся те объекты, тип которых начинается с указанного префикса.");
			FNC_IN  (MOD_MetaObject, objFirstNo, "Номер объекта, начиная с которого выводятся объекты функцией Enumerate(). По умолчанию равен 0.");
			FNC_IN  (MOD_MetaObject, objLastNo, "Номер объекта, до которого включительно выводятся объекты функцией Enumerate(). По умолчанию равен последнему порядковому номеру.");
			FNC_OUT (MOD_MetaObject, objIDs, "Массив идентификаторов перечисленных объектов.");
			FNC_OUT (MOD_MetaObject, objTypes, "Массив типов метаобъектов.");
			FNC_OUT (MOD_MetaObject, objNames, "Массив названий перечисленных объектов.");
			FNC_OUT (MOD_MetaObject, objSysNames, "Массив системных имён метаобъектов.");
			FNC_OUT (MOD_MetaObject, objProxyIDs, "Для семантической сети -- массив идентификаторов соответствующих прокси-объектов.");
			FNC_OUT (MOD_MetaObject, TotalStoredNum, "Сколько всего объектов может быть перечислено в данных условиях.");
			FNC_OUT (MOD_MetaObject, MaxNumInQuery, "Максимально допустимое число запрашиваемых за один раз объектов.");
			FNC_OUT (MOD_MetaObject, ExitCode, "Код возврата.");
			FNC_OUT (MOD_MetaObject, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_MetaObject_GetData, "Получение данных о Метаобъекте.");
			FNC_IN  (MOD_MetaObject, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право чтения [R].");
			FNC_IN  (MOD_MetaObject, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_MetaObject, objID, "Идентификатор запрашиваемого объекта.");
			FNC_OUT (MOD_MetaObject, ProxyID, "Для семантической сети -- идентификатор соответствующего прокси-объекта.");
			FNC_OUT (MOD_MetaObject, Type, "Тип объекта.");
			FNC_OUT (MOD_MetaObject, Name, "Имя объекта.");
			FNC_OUT (MOD_MetaObject, SysName, "Системное название объекта.");
			FNC_OUT (MOD_MetaObject, FeodIDs, "Зоны доступа, к которым принадлежит метаобъект {Concept.Feod.Semantic}.");
			FNC_OUT (MOD_MetaObject, ReadOnly, "Имеет ли пользователь право редактировать объект");
			FNC_OUT (MOD_MetaObject, ExitCode, "Код возврата.");
			FNC_OUT (MOD_MetaObject, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_MetaObject_PutData, "Изменение данных Метаобъекта.");
			FNC_IN  (MOD_MetaObject, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право записи [W].");
			FNC_IN  (MOD_MetaObject, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_MetaObject, objID, "Идентификатор изменяемого объекта.");
			FNC_IN  (MOD_MetaObject, Type, "Тип метаобъекта.");
			FNC_IN  (MOD_MetaObject, Name, "Название метаобъекта.");
			FNC_IN  (MOD_MetaObject, SysName, "Системное название метаобъекта, строится как переменная С++. Если не пусто, то имя должно быть уникально внутри типа.");
			FNC_IN  (MOD_MetaObject, FeodIDs, "Зоны доступа, к которым принадлежит метаобъект {Concept.Feod.Semantic}.");
			FNC_OUT (MOD_MetaObject, ExitCode, "Код возврата.");
			FNC_OUT (MOD_MetaObject, ExitCodeComment, "Текстовый комментарий к коду возврата.");
      FNC        (MOD_MetaObject_Delete, "Удаление Метаобъекта.");
			FNC_IN  (MOD_MetaObject, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен иметь право удаления [D].");
			FNC_IN  (MOD_MetaObject, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_MetaObject, objID, "Идентификатор удаляемого объекта.");
			FNC_OUT (MOD_MetaObject, ExitCode, "Код возврата.");
			FNC_OUT (MOD_MetaObject, ExitCodeComment, "Текстовый комментарий к коду возврата.");

   // UserProfile
      FNC        (MOD_UserProfile_GetData, "Получение данных из профилей пользователей.");
			FNC_IN  (MOD_UserProfile, Login, "Логин пользователя, запрашивающего операцию. Пользователь должен обладать правами просматривать данные пользователей и обладать более высоким уровнем доступа, или быть самим пользователем.");
			FNC_IN  (MOD_UserProfile, Password, "Пароль пользователя, запрашивающего операцию.");
			FNC_IN  (MOD_UserProfile, objID, "Идентификатор пользователя, чей профайл запрашивается.");
			FNC_OUT (MOD_UserProfile, Log_ObjectClassIDs, "Список идентификаторов классов объектов, которые изменял (удалял, добавлял ...) пользователь");
			FNC_OUT (MOD_UserProfile, Log_ObjectClassNames, "Список имен классов объектов, которые изменял (удалял, добавлял ...) пользователь");
			FNC_OUT (MOD_UserProfile, Log_ObjectIDs, "Список идентификаторов объектов, которые изменял (удалял, добавлял ...) пользователь");
			FNC_OUT (MOD_UserProfile, Log_ObjectNames, "Список имен объектов, которые изменял (удалял, добавлял ...) пользователь");
			FNC_OUT (MOD_UserProfile, Log_ActionCodes, "Список кодов действий, которые совершал пользователь");
			FNC_OUT (MOD_UserProfile, Log_ActionDescriptions, "Расшифровки кодов действий");
			FNC_OUT (MOD_UserProfile, Log_Times, "Времена совершения действий, которые совершал пользователь");
			FNC_OUT (MOD_UserProfile, ExitCode, "Код возврата.");
			FNC_OUT (MOD_UserProfile, ExitCodeComment, "Текстовый комментарий к коду возврата.");
   }
// Вызов обнаруженной функции или сообщение об ошибке.
   FNC_END;
}
//____________________________________________________________________________[]




